version: '3.4'

services:
  src:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - RABBITMQ_HOSTNAME=rabbit
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - ENVIRONMENT_MODE=dev
networks:
  default:
    external:
      # Connecting to the same network where rabbitMQ is running (Checkout the rabbit_event_stream project https://github.com/mail4hafij/rabbit_event_stream)
      name: rabbit_event_stream
volumes:
  logs: